<?php
/*
 * This is the child theme for Total theme, generated with Generate Child Theme plugin by catchthemes.
 *
 * (Please see https://developer.wordpress.org/themes/advanced-topics/child-themes/#how-to-create-a-child-theme)
 */
add_action( 'wp_enqueue_scripts', 'totalchild_enqueue_styles' );
function totalchild_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'bootstrap-theme', get_stylesheet_directory_uri() . '/assets/css/bootstrap.min.css', array('parent-style'));
    wp_enqueue_style( 'font-icons', get_stylesheet_directory_uri() . '/assets/css/font-icons.css', array('parent-style'));
    wp_enqueue_style( 'theme-style', get_stylesheet_directory_uri() . '/assets/css/theme-style.css', array('parent-style'));

    //wp_enqueue_style( 'child-style', get_stylesheet_directory_uri() . '/style.css', array('parent-style'));

    wp_enqueue_script('modernizr-js', get_stylesheet_directory_uri() . '/assets/js/modernizr.min.js', array('jquery'), false, true);
    wp_enqueue_script('calc_script-js', get_stylesheet_directory_uri() . '/assets/js/calc_script.js', array('jquery'), false, true);
    wp_enqueue_script('scripts-js', get_stylesheet_directory_uri() . '/assets/js/scripts.js', array('jquery'), false, true);
}
/*
 * Your code goes below
 */
//  Actions
add_action( 'widgets_init', 'cust_widgets' );


// Some weare
function cust_widgets(){
    register_sidebar([
        'name' => 'Виджет для размещения копирайта',
        'id' => 'cust_footer_1',
        'before_widget' => null,
        'after_widget' => null,
    ]);
    register_sidebar([
        'name' => 'Сайдбар блок 1',
        'id' => 'cust_sidebar_1',
        'before_widget' => null,
        'after_widget' => null,
    ]);
    register_sidebar([
        'name' => 'Сайдбар блок 2',
        'id' => 'cust_sidebar_2',
		'before_widget' => '<aside id="%1$s" class="footer-widget widget widget__custom-block %2$s clr">',
		'after_widget'  => '</aside>',
		'before_title'  => '<p class="widget-title">',
		'after_title'   => '</p>',
    ]);
}

function mw_faqhook_page_1678796223196() { 
    if(is_page ("3539")){ 
    ?> 
    <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Через сколько времени после заказа можно будет получить аттестат?","acceptedAnswer":[{"@type":"Answer","text":"Мы изготавливает документы в течение трех дней. А вот время доставки зависит от разных факторов, в частности, от вашего месторасположения. Предполагаемое время доставки лучше уточнить у менеджера."}]},{"@type":"Question","name":"Как заказать документ об образовании у вас?","acceptedAnswer":[{"@type":"Answer","text":"Для этого нужно будет заполнить специальную форму на нашем сайте, либо связаться с нашим менеджером по телефону."}]},{"@type":"Question","name":"А что, если аттестат проверят на подлинность?","acceptedAnswer":[{"@type":"Answer","text":"Такая вероятность существует, но она не так велика. Для проверки аттестата на подлинность нужно обращаться в то учебное заведение, где он был выдан. А это занимает определенное время."}]},{"@type":"Question","name":"У меня есть аттестат, но приложение к нему потерял. Можно купить только приложение?","acceptedAnswer":[{"@type":"Answer","text":"Да. У нас можно купить отдельно только приложение для с нужными вам оценками. Но понадобится отсканированное фото аттестата – для соответствия."}]},{"@type":"Question","name":"Я живу в Уфе. Вы сможете доставить заказ в мой город?","acceptedAnswer":[{"@type":"Answer","text":"Мы доставляем заказы почти во все городам России."}]},{"@type":"Question","name":"Какие гарантии того, что документ будет получен, вы даете?","acceptedAnswer":[{"@type":"Answer","text":"Мы не требуем у своих покупателей предоплаты. Вы оплачиваете заказ во время его получения."}]},{"@type":"Question","name":"Как оплатить заказ?","acceptedAnswer":[{"@type":"Answer","text":"Оплата заказ – после его получения. Вы можете заплатить наличными или перевести деньги на карту."}]},{"@type":"Question","name":"Во сколько обойдется аттестат у вас?","acceptedAnswer":[{"@type":"Answer","text":"Все зависит от конкретного вида диплома. На нашем сайте указаны цены к разным вариантам документов об образовании."}]},{"@type":"Question","name":"В документе опечатка, как быть?","acceptedAnswer":[{"@type":"Answer","text":"Если бы обнаружили у приобретенном у нас документе опечатку, обращайтесь к нам. Мы бесплатно и оперативно исправим ошибку и предоставим вам правильный образец документа."}]},{"@type":"Question","name":"Вы сможете делать советский аттестат?","acceptedAnswer":[{"@type":"Answer","text":"Да, мы изготавливаем на заказ аттестаты старого советского образца."}]}]}</script><!-- Generated by https://www.matthewwoodward.co.uk/ --> 
    <?php 
    } 
    } 
add_action("wp_head", "mw_faqhook_page_1678796223196");

//Shortcods
add_shortcode( 'si-section-action', 'si_section_action' );
function si_section_action( $attr ){
    $params = shortcode_atts([
        'text' => '',
    ], $attr);

    return '<section class="section actions-posts mt-40 mb-0" style="background: url(https://kupit-attestat.org/wp-content/themes/totalchild/assets/img/content-action-bg.jpg); background-repeat: no-repeat;">
    <div class="content-action">
      <div class="content-action-title">Акции и скидки:</div>
      <div class="content-action-container">
        <div class="content-action-item">При повторной покупке – скидка 2 тысячи рублей;</div>
        <div class="content-action-item">Скидка для именинников – 1 тысяча рублей. Действует за три дня до и после дня рождения;</div>
        <div class="content-action-item">При покупке двух и больше документов – скидка 2 тысячи рублей с каждого.</div>
      </div>
    </div>
  </section>';
}

// Нумерация в пагинации для Description в плагин Yoast
add_filter('wpseo_metadesc', 'add_page_number_to_description');
function add_page_number_to_description($description) {
    if (is_paged()) {
        global $wp_query;
        $paged = $wp_query->query_vars['paged'];
        $description .= ' - Страница ' . $paged;
    }
    return $description;
}


/**
 * Изменяет хлебные крошки Yoast.
 *
 * Вывести в шаблоне: do_action('pretty_breadcrumb');
 * https://wp-kama.ru/plugin/yoast/kak-izmenit-vyorstku-hlebnyh-kroshek-yoast-na-svoyu
 */
class Pretty_Breadcrumb
{

    /**
     * Какую позицию занимает элемент в цепочке хлебных крошек.
     *
     * @var int
     */
    private $el_position = 0;

    public function __construct()
    {
        add_action('pretty_breadcrumb', [$this, 'render']);
    }

    /**
     * Выводит на экран сгенерированные крошки.
     *
     * @return void
     */
    public function render()
    {
        if (!function_exists('yoast_breadcrumb')) {
            return;
        }

        // Регистрируем фильтры для изменения дефолтной вёрстки крошек
        add_filter('wpseo_breadcrumb_single_link', [$this, 'modify_yoast_items'], 10, 2);
        add_filter('wpseo_breadcrumb_output', [$this, 'modify_yoast_output']);
        add_filter('wpseo_breadcrumb_output_wrapper', [$this, 'modify_yoast_wrapper']);
        add_filter('wpseo_breadcrumb_separator', '__return_empty_string');

        // Выводим крошки на экран
        yoast_breadcrumb();

        // Отключаем фильтры
        remove_filter('wpseo_breadcrumb_single_link', [$this, 'modify_yoast_items']);
        remove_filter('wpseo_breadcrumb_output', [$this, 'modify_yoast_output']);
        remove_filter('wpseo_breadcrumb_output_wrapper', [$this, 'modify_yoast_wrapper']);
        remove_filter('wpseo_breadcrumb_separator', '__return_empty_string');

        // Обнуляем счётчик
        $this->el_position = 0;
    }

    /**
     * Изменяет html код li элементов.
     *
     * @param string $link_html Дефолтная вёрстка элемента хлебных крошек.
     * @param array $link_data Массив данных об элементе хлебных крошек.
     *
     * @return string
     */
    function modify_yoast_items($link_html, $link_data)
    {
        // Шаблон контейнера li
        $li = '<span itemprop="itemListElement" itemscope="itemscope" itemtype="https://schema.org/ListItem" %s>%s</span>';

        // Содержимое li в зависимости от позиции элемента
        if (strpos($link_html, 'breadcrumb_last') === false) {
            $li_inner = sprintf('
                <a itemprop="item" href="%s" class="pathway">
                    <span itemprop="name">%s</span>
                </a>
            ', $link_data['url'], $link_data['text']);
            $li_inner .= '<span class="divider"> / </span>';
            $li_class = '';
        } else {
            $li_inner = sprintf('<span itemprop="name">%s</span>', $link_data['text']);
            $li_class = 'class="active"';
        }

        $li_inner .= sprintf('<meta itemprop="position" content="%d"/>', ++$this->el_position);

        // Вкладываем сформированное содержание в li и возвращаем полученный элемент хлебных крошек.
        return sprintf($li, $li_class, $li_inner);
    }

    /**
     * Возвращает псевдо wrapper, который в будущем будет вырезан из вёрстки.
     * Если этого не сделать, то будущие li будут обёртнуты в единый span Yoast'ом.
     *
     * @return string
     */
    function modify_yoast_wrapper()
    {
        return 'wrapper'; // Будущий "уникальный" тег для вырезки из html
    }

    /**
     * Изменяет дефолтный html код крошек Yoast.
     *
     * @param string $html
     *
     * @return string
     */
    function modify_yoast_output($html)
    {
        // Убираем псевдо wrapper
        $html = str_replace(['<wrapper>', '</wrapper>'], '', $html);

        // Формируем контейнер для li элементов
        $ul = '<nav itemscope="itemscope" itemtype="https://schema.org/BreadcrumbList" class="breadcrumb site-breadcrumbs wpex-clr hidden-phone position-absolute has-js-fix">%s</nav>';

        // Вставляем в контейнер li элменты
        $html = sprintf($ul, $html);

        return $html;
    }
}

new Pretty_Breadcrumb();

// Woocommerce

// Add PopUp link before add_to_cart

function custom_link_before_add_to_cart_form() {
    echo '<a href="#" class="btn-product popmake-7043">Заказать</a>';
}
add_action( 'woocommerce_before_add_to_cart_form', 'custom_link_before_add_to_cart_form' );